- name: "Provision Image"
  hosts: default
  become: true

  tasks:
    - name: add apt boundary signing key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: add apt boundary repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main"
        state: present

    - name: install boundary
      apt:
        name: boundary
        state: present

    - name: add boundary user
      user:
        name: boundary
        group: boundary
        system: true
        comment: Boundary

    - name: add boundary service
      ansible.builtin.copy:
        dest: "/etc/systemd/system/boundary.service"
        content: |
          [Unit]
          Description=Boundary

          [Service]
          ExecStart=/usr/bin/boundary server -config /etc/boundary-controller.hcl
          User=boundary
          Group=boundary
          LimitMEMLOCK=infinity
          Capabilities=CAP_IPC_LOCK+ep
          CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK

          [Install]
          WantedBy=multi-user.target
        owner: boundary
        group: boundary
        mode: "0664"

    - name: enable boundary service
      ansible.builtin.service:
        name: boundary
        enabled: true

